name: Build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: "${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}"
  cancel-in-progress: true

jobs:
  build:
    strategy:
      matrix:
        os:
          - macos-latest
          #- ubuntu-latest
          #- windows-latest
      fail-fast: false
    runs-on: ${{ matrix.os }}
    env:
      FDB_VERSION: '7.3.69'

    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 2

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 21

      - name: Validate Gradle wrapper
        uses: gradle/actions/wrapper-validation@v4

      - name: Detect Kotlin version
        id: detect-kotlin
        shell: bash
        run: |
          if [[ -f gradle/libs.versions.toml ]]; then
            V=$(grep -E '^[[:space:]]*kotlin[[:space:]]*=\s*"[0-9]+(\.[0-9]+)*"' -m1 gradle/libs.versions.toml | sed -E 's/.*"([0-9]+(\.[0-9]+)*)".*/\1/')
          else
            V=$(grep -R -E '^[[:space:]]*kotlin\.version[[:space:]]*=' -m1 **/gradle.properties | head -n1 | sed -E 's/.*=[[:space:]]*([0-9]+(\.[0-9]+)*).*/\1/')
          fi
          echo "KOTLIN_VERSION=${V:-unknown}" >> "$GITHUB_ENV"

      - name: Cache Kotlin/Native dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.konan/dependencies/**
            ~/.konan/kotlin-native-prebuilt-*
          key: konan-deps-${{ runner.os }}-${{ runner.arch }}-${{ env.KOTLIN_VERSION }}
          restore-keys: |
            konan-deps-${{ runner.os }}-${{ runner.arch }}-
            konan-deps-${{ runner.os }}-

      - name: Cache FoundationDB binaries
        uses: actions/cache@v4
        with:
          path: |
            store/foundationdb/bin/**
          key: fdb-${{ runner.os }}-${{ env.FDB_VERSION }}-${{ hashFiles('store/foundationdb/scripts/install-foundationdb.sh') }}
          restore-keys: |
            fdb-${{ runner.os }}-

      - name: Cache Kotlin Konan
        id: cache-kotlin-konan
        uses: actions/cache@v4
        with:
          path: |
            ~/.konan/**/*
          key: kotlin-konan-${{ runner.os }}-${{ hashFiles('**/gradle.properties') }}-${{ hashFiles('**/gradle/libs.versions.toml') }}
          restore-keys: |
            kotlin-konan-${{ runner.os }}-${{ hashFiles('**/gradle.properties') }}-
            kotlin-konan-${{ runner.os }}-

      - uses: gradle/actions/setup-gradle@v4
        with:
          gradle-home-cache-cleanup: true
          cache-read-only: ${{ github.event_name == 'pull_request' }}

      - name: Build the project
        env:
          GRADLE_OPTS: -Dorg.gradle.jvmargs=-Xmx3g
        run: ./gradlew build --stacktrace --parallel --build-cache
