name: Publish
on:
  workflow_run:
    workflows: [ Build ]
    branches: [ master ]
    types: [ completed ]
  workflow_dispatch:

concurrency:
  group: "${{ github.workflow }}"
  cancel-in-progress: false

jobs:
  maven-publish:
    runs-on: macos-latest # macOS supports building all Kotlin targets
    if: ${{ github.event.workflow_run.conclusion == 'success' }} # only publish if the 'Build' workflow passed
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v5

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 21

      - name: Validate Gradle wrapper
        uses: gradle/actions/wrapper-validation@v4

      - name: Cache Kotlin Konan
        id: cache-kotlin-konan
        uses: actions/cache@v4
        with:
          path: |
            ~/.konan/**/*
          key: kotlin-konan-${{ runner.os }}

      - uses: gradle/actions/setup-gradle@v4
        with:
          gradle-home-cache-cleanup: true

      - name: Build the project
        # Maven Central _really_ doesn't like parallel uploads, so disable parallelization
        run: ./gradlew publish --no-configuration-cache --no-parallel
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.MAVENCENTRAL_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.MAVENCENTRAL_PASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{secrets.MARYK_SIGNING_KEY}}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{secrets.MARYK_SIGNING_PASSWORD}}
