# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Run tests on commit and PR to master

on:
  push:
    branches: [ master, function_mangling_issues ]
  pull_request:
    branches: [ master, function_mangling_issues ]

jobs:
  test-jvm:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Run kotlin JVM tests
        run: ./gradlew jvmTest
      - name: Run kotlin JS tests
        run: ./gradlew jsTest
